### ISSUE TITLE
optionalFeatures: cameraAccess

### ISSUE THREAD

**Issue by De-Panther** [bialpio/webxr-raw-camera-access#2]
If `cameraAccess` is requested as part of the `optionalFeatures`, can the user allow other AR session required/optional features, but deny `cameraAccess`?
Or is it "All or nothing"?

Also, is there a chrome version in which we can test this?

Thanks

**Comment by bialpio** [comment]
Currently in our implementation in Chrome for Android, it's "all or nothing" (we will display only one permission prompt that is customized depending on the features that the site requests).

The feature should be useable in M86 & above, but it does require WebXRIncubations flag to be enabled in chrome://flags.

**Comment by De-Panther** [comment]
Thanks.
The demo at https://storage.googleapis.com/chromium-webxr-test/r827010/proposals/camera-access-barebones.html works well on my device (Galaxy s10e)

**Comment by bialpio** [comment]
Resolving. One more note regarding the "all or nothing": we usually do not mandate expicitly how the UAs are supposed to ask for consent, so my response is very Chrome-specific.
